#!/bin/bash

export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$(cat $AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_FP)
export AIRFLOW__CELERY__RESULT_BACKEND=$(cat $AIRFLOW__CELERY__RESULT_BACKEND_FP)
export AIRFLOW__CELERY__BROKER_URL=$(cat $AIRFLOW__CELERY__BROKER_URL_FP)

exec /entrypoint "$@"
