name: Build and Push Docker Image to GHCR

on:
    push:
        branches:
        - main

jobs:
    build-and-push:
    runs-on: ubuntu-latest

	permissions:
        contents: read
        packages: write
	
	env:
        IMAGE_PREFIX: ghcr.io/fineyoungcannibals
	
	steps:
		- name: Checkout code
		  uses: actions/checkout@v3

		- name: Set up Docker Buildx
		  id: buildx
		  uses: docker/setup-buildx-action@v3
    
        - name: Log in to GHCR
		  uses: docker/login-action@v3
		  with:
		    registry: ghcr.io
			username: ${{ github.actor }}
			password: ${{ secrets.GHCR_AIRFLOW_PAT }}

        - name: Set lowercase repo name
		run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

		# images follow here
		# airflow-cli
		- name: Build and push image from Dockerfile.airflowcli
		  uses: docker/build-push-action@v5
		  with:
		     context: .
			 file: Dockerfile.airflowcli
			 push: true
			 builder: ${{ steps.buildx.outputs.name }}
			 cache-from: type=gha
             cache-to: type=gha,mode=max
			 tags: |
			   ${{ env.IMAGE_PREFIX }}/airflow:latest
			   ${{ env.IMAGE_PREFIX }}/airflow:${{ github.sha }}
		# airflow-webserver
		# airflow-scheduler
        # airflow-init
		# airflow-triggerer
		# airflow-worker
		# flower
