name: Mirror Airflow Image to GHCR

on:
  push:
    branches: [main]

jobs:
  push-airflow-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull official Apache Airflow image
        run: docker pull apache/airflow:2.10.5

      - name: Tag image for GHCR
        run: docker tag apache/airflow:2.10.5 ghcr.io/fineyoungcannibals/airflow:2.10.5

      - name: Set up Docker Buildx
	    uses: docker/setup-buildx-action@v3

      - name: Build and Push to GHCR with image caching
	    uses: docker/build-push-action@v5
		with: 
		   context: .
		   file: Dockerfile
		   push: true
		   builder: ${{ steps.buildx.outputs.name }}
		   cache-from: type=gha
		   cache-to: type=gha,mode=max
		   tags: ${{ env.IMAGE_TAG }}
