name: Mirror Airflow Image to GHCR

on:
  push:
    branches: [main]

jobs:
  push-mirror-airflow-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
         run: |
          IMAGE_TAG="ghcr.io/${GITHUB_REPOSITORY,,}:2.10.5"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
         shell: bash

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to GHCR with image caching
        uses: docker/build-push-action@v5
    	with: 
           context: .
           file: Dockerfile
           push: true
           builder: ${{ steps.buildx.outputs.name }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
           tags: ${{ env.IMAGE_TAG }}
