name: Rebuild on dependency update

on: 
  repository_dispatch:
    types: [regexlibrary_updated]

jobs:
  rebuild-iamge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to GHCR with image caching
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/fineyoungcannibals/prod-custom-airflow:latest
